baseURL = 'https://wattie.dev/'
languageCode = 'en-NZ'
title = 'Benjamin Wattie'
enableEmoji = true
copyright = "Copyright ©2021-, Jam Wattie; All rights reserved."

[server]
[[server.headers]]
  for = '/**'
  [server.headers.values]
    Cache-Control = 'public, max-age=86400'
    Content-Security-Policy = 'script-src self'
    Referrer-Policy = 'strict-origin'
    X-Content-Type-Options = 'nosniff'
    X-Frame-Options = 'DENY'
    X-XSS-Protection = '1; mode=block'
    Strict-Transport-Security = 'max-age=31536000; includeSubDomains; preload'

[params]
  description = "Jamjamjam"

  # Author
  author      = "Jam"
  authorDesc  = "Jamjamjam"
  imgPath = "img"

  markupImgClass = "borderless"

  # This will append a separator (of your choice) along the site title to your <title>
  # ie.: | ❚ - – — • ⚫
  # You can disabled it PER PAGE by using "disableTitleSeparator" at front
  # matter or disable it entirely by commenting the line below
  titleSeparator = "|"